#!/bin/bash
exec java \
  --add-exports java.base/jdk.internal.math=io.questdb \
  -Dcontainerized=true \
  -ea \
  -XX:ErrorFile=/var/lib/questdb/db/hs_err_pid+%p.log \
  -XX:+AlwaysPreTouch \
  -XX:+UseG1GC \
  -XX:+ExitOnOutOfMemoryError \
  -XX:MaxRAMPercentage=70 \
  -XX:InitialRAMPercentage=25 \
  -p /opt/questdb/questdb.jar \
  -m io.questdb/io.questdb.ServerMain \
  -d /var/lib/questdb \
  -f > /app/logs/questdb.log 2>&1
